version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: "docker-compose"
          command: docker-compose up -d --build
      - run: 
          name: "chmod-dotnet-install"
          command: chmod +x
      - run: 
          name: "chmod-dotnet-install"
          command: ./dotnet-install.sh --channel LTS
